# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - web-more-speakers
run-name: >
  Webapp Deploy - '${{ github.event.head_commit.message }}',
  from ${{ github.ref }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: web-more-speakers
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 10.0.x
  WORKING_DIRECTORY: ./src/MoreSpeakers.Web/

jobs:
  determine-version:
    name: Determine next version number.
    uses: ./.github/workflows/determine-next-release-version.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: determine-version
    permissions:
      contents: read  # This is required for actions/checkout
    outputs:
      artifact_name: ${{ steps.output-artifact-name.outputs.artifact_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: >
          dotnet build "${{ env.WORKING_DIRECTORY }}"
          --configuration ${{ env.CONFIGURATION }}
          --no-restore
          -p:Version=${{ needs.determine-version.outputs.version }}
          -p:VersionPrefix=${{ needs.determine-version.outputs.version }}

      - name: Publish
        run: >
          dotnet publish "${{ env.WORKING_DIRECTORY }}"
          --configuration ${{ env.CONFIGURATION }}
          --no-build
          --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          include-hidden-files: true

      - name: Output artifact name
        id: output-artifact-name
        run: |
          echo "artifact_name=webapp" >> $GITHUB_OUTPUT

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, determine-version]
    permissions:
      contents: write  # to be able to publish a GitHub release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Tag
        id: create-tag
        run: |
          git tag v${{ needs.determine-version.outputs.version }}
            echo "tag=\
            v${{ needs.determine-version.outputs.version }}" \
            >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create-webapp-release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create-tag.outputs.tag }}
          release_name: Release ${{ steps.create-tag.outputs.tag }}
          body: |
            Release created automatically by GitHub Actions.
          draft: false

      - name: download artifact for Release
        id: download-artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: ./Release

      - name: create zip
        run: |
          (cd Release && zip -r ${{ needs.build.outputs.artifact_name }}.zip .)

      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-webapp-release.outputs.upload_url }}
          asset_path: Release/${{ needs.build.outputs.artifact_name }}.zip
          asset_name: ${{ needs.build.outputs.artifact_name }}.zip
          asset_content_type: application/zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7DC7A7F6967B4966911EEDE455999FB5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F54FBBE9F2FB49F9B1B4F25144C0529A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A568104651C84976894442C1226EEF06 }}


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          slot-name: Production
